# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[project]
name = "camscan"
description = "Camscan is an application for scanning documents using a camera connected to your computer."
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE.md" }
dynamic = ["version"]
requires-python = ">= 3.14"
dependencies = [
    "customtkinter",
    "numpy",
    "opencv-python",
    "cv2_enumerate_cameras",
    "Pillow",
]

[dependency-groups]
dev = [
    { include-group = "ruff" },
    { include-group = "test" },
    { include-group = "mypy" },
    { include-group = "pydoclint" },
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "pyinstaller",
]
ruff = ["ruff>=0.16.1"]
test = ["pytest"]
mypy = ["mypy>=2.3.0", "types-pyinstaller>=6.21.0.20260616"]
pydoclint = ["pydoclint>=0.9.1"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { attr = "camscan.__version__" }

[tool.setuptools.packages.find]
include = ["camscan"]

[tool.ruff]
exclude = [".venv"]
line-length = 88
indent-width = 4
target-version = "py314"

[tool.mypy]
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = [
    "customtkinter", # No stub files available
]
ignore_missing_imports = true

[tool.pydoclint]
style = "sphinx"
require-return-section-when-returning-nothing = false
arg-type-hints-in-signature = true
arg-type-hints-in-docstring = false
check-return-types = false
check-class-attributes = false
exclude = ".venv"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
markers = [
    "integration: Integration tests (deselect with '-m \"not integration\"')",
]
