name: black

on: [push]

permissions:
  contents: write

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
